### ISSUE TITLE
Monster class being mistaken as Prestige Class.

### ISSUE THREAD

**Issue by classicrp** [Lavaeolous/PF1-StatBlock-Converter-Module#318]
Running through more of the encounters of AP62 - Part 3 - Level K (Shattered Star; Curse of the Lady's Light; Dungeon Level 1) and ran into and issue importing a "Marble Sentinel", small construct.  Looking at the console (attached) it is using the configured regex to pull apart a that name which happens to match part of itself with the "Sentinel" (https://www.d20pfsrd.com/classes/prestige-classes/other-paizo/s-z/sentinel/) prestige class.

To check, I renamed it to "Marble Sentniel" and got passed the class issue.  BTW, Is it supposed to rebuild "formattedInput" object when you select either of the "Import" options? It does.  
Anyway, I continued following the "dataOutput" object to see if it still breaks on import;

- Noticed that you catch Darkvision but the PF1.token object has no Darkvision only .dimSight (5e Darkvision) and .brightSight(PF1 Darkvision). 
  #2497    `dataOutput.token.brightSight = 0;`  
  replace `0` with `rangeDarkvision` 
  idea?

- Noticed a search through all game folders. 
  #5008    `let searchForFolder = await game.folders.find(entry => entry.data.name === "sbc | Imported Creatures"); `  
  append ` && entry.data.name === "Actor"` before `);` 
  faster?

The rest was flawless.
P.S. bought you 3 coffees!

![sbs js_20201028_eror-out](https://user-images.githubusercontent.com/12385879/97506111-91418380-1950-11eb-9f1c-9f90117ea5a9.jpg)
 
![sbs js_20201028_L1112](https://user-images.githubusercontent.com/12385879/97505687-be416680-194f-11eb-80cd-388d2e4f2f5c.jpg)

[1_Marble_Sentinel_x3.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/5455256/1_Marble_Sentinel_x3.txt)

[fvtt-Actor-Marble_Sentinel_x3.json.txt](https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module/files/5455490/fvtt-Actor-Marble_Sentinel_x3.json.txt)

**Comment by Lavaeolous** [comment]
Wow, thanks for the detailed feedback and the coffees!
The issue with names clashing with classes (and/or races) was fixed yesterday and should be up in 2.0.7. I had a "Dwarf Caiman" an aquatic animal that always got imported as a dwarf. The fix is not very readable (as i just remove the name from the generalData after parsing it), but the whole section is in dire need of refactoring.

I'll have to check why formattedInput gets rebuild. The preview was a late addition to sbc (with v2.0.0), so its more spaghetti code than anything else. As is most of the code (i'm have no formal background in software development / programming).

As for token vision settings: I've set that to 0 after user feedback from discord, if i remember correctly because stuff got bogged down with many tokens present and most gms ignoring token vision for monsters. I'll have to check how thats looking after 0.7.5.

The fix for the folder search is deeply appreciated! I'll include that in v2.0.7

Thanks again!

**Comment by classicrp** [comment]
Happy to help.

**Comment by Lavaeolous** [comment]
I think this
`&& entry.data.name === "Actor"`
should be
`&& entry.data.type === "Actor"`

correct?

**Comment by classicrp** [comment]
Yes. Absolutely. Sorry for the typo.

**Comment by Lavaeolous** [comment]
Fixed/Implemented in 2.0.7
