### ISSUE TITLE
Post Statblocks that break SBC v3.0.0-alpha.3 here!

### ISSUE THREAD

**Issue by Lavaeolous** [Lavaeolous/PF1-StatBlock-Converter-Module#350]
Post Statblocks that break the current alpha of version 3.0.0 here.
Keep in mind that currently, offensive data **does not get parsed**!

**Comment by danhatch91** [comment]
LAMM’S LAMB CR 1/3 XP 135 Young human expert 1 N Small humanoid (human)Init +3; Senses Perception +2 DEFENSE AC 14, touch 14, flat-footed 11 (+3 Dex, +1 size)hp 5 (1d8+1)Fort +0, Ref +3, Will +0 OFFENSE Speed 30 ft. Melee dagger –1 (1d3–2/19–20) or pitchfork –7 (1d6–2)Space 5 ft.; Reach 5 ft. (10 ft. with pitchfork)TACTICS During Combat Typically an orphan spends the first round of combat in shock and surprise, although once a few battles have broken out in the fishery, feel free to have the orphans react more quickly. The orphans prefer to attack with the long pitchforks they use to load and unload fish (these pitchforks function as improvised weapons with reach), but they switch to daggers if anyone is able to get inside their reach.Morale An orphan who takes any damage attempts to flee to area A8, unless all of Gaedren’s thugs are either dead or out of sight, in which case the orphan abandons the fishery entirely into the surrounding slums.STATISTICS Str 7, Dex 16, Con 11, Int 11, Wis 6, Cha 10 Base Atk +0; CMB –3; CMD 10 Feats Skill Focus (Acrobatics), Skill Focus (Sleight of Hand)Skills Acrobatics +10, Bluff +4, Climb +2, Escape Artist +7, Perception +2, Sleight of Hand +10, Stealth +8 Languages Common Gear dagger, pitchfork

**Comment by Lavaeolous** [comment]
> Having trouble with the statblock below. Thanks for any help :)
> 
> LAMM’S LAMB

At least for this statblock: SBC **needs** linebreaks, so if you copy & paste you need to keep them intact. When copying from PDFs you may need to manually fix linebreaks, as PDFs are formatted for visual, not structural coherency.

**Comment by danhatch91** [comment]
Cheers mate! Appreciate it. I'll give it a try tonightSent from my Galaxy
-------- Original message --------From: Lavaeolous <notifications@github.com> Date: 26/01/2021  08:26  (GMT+00:00) To: Lavaeolous/PF1-StatBlock-Converter-Module <PF1-StatBlock-Converter-Module@noreply.github.com> Cc: danhatch91 <hatchdaniel@live.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [Lavaeolous/PF1-StatBlock-Converter-Module] Post Statblocks that break SBC v3.0.0-alpha.2 here! (#350) 



Having trouble with the statblock below. Thanks for any help :)

LAMM’S LAMB



At least for this statblock: SBC needs linebreaks, so if you copy & paste you need to keep them intact. When copying from PDFs you may need to manually fix linebreaks, as PDFs are formatted for visual, not structural coherency.

**Comment by Hanhula** [comment]
```
Cid La Flaga
Male ghoran gunslinger 11/shieldmarshal 3/Champion 2
CN Medium plant
Init +12; Senses darkvision 120 ft., low-light vision; Perception +19 (+20 when opposed by another creature's Disguise or Sleight of Hand checks)
Defense
AC 33, touch 22, flat-footed 23 (+9 armor, +7 Dex, +3 dodge, +2 natural, +2 shield)
hp 115 (14d10+38)
Fort +15, Ref +21, Will +15; +1 bonus vs. Ruben Goldblood and his minions.
Defensive Abilities hard to kill, nimble +3
Weaknesses delicious, light dependent
Offense
Speed 30 ft.
Melee cold iron dagger +14/+9/+4 (1d4/19-20) or
   dagger +14/+9/+4 (1d4/19-20) or
   dagger +14/+9/+4 (1d4/19-20) or
   silver dagger +14/+9/+4 (1d4-1/19-20)
Ranged +3 reliable, greater pistol +25 (1d8+10/×4) or
   buckler gun +21/+16/+11 (1d6/×4) or
   dragon pistol +21 (1d6/×4) or
   musket +21 (1d12/×4)
Special Attacks champion's strike (distant barrage), deeds (bleeding wound, dead shot, deadeye, deadeye, expert loading, gunslinger initiative, gunslinger's dodge, gunslinger's dodge, lightning reload, pistol-whip, quick clear, quick clear, startling shot, targeting, utility shot), grit (3), gun training +7 (pistol, rifle), mythic power (7/day, surge +1d6)
Spell-Like Abilities (CL 14th; concentration +16)
   1/day—detect poison, goodberry (sprout from own body), purify food and drink (DC 12)
Statistics
Str 10, Dex 24, Con 15, Int 12, Wis 16, Cha 14
Base Atk +14; CMB +14; CMD 34
Feats Clustered Shots, Deadly Aim, Gunsmithing, Point-Blank Shot, Precise Shot, Quick Draw, Rapid Reload, Rapid Shot[M], Snap Shot, Vengeance, Weapon Focus (pistol)
Traits anatomist, seeker
Skills Acrobatics +12, Appraise +2, Bluff +10 (+11 in Alkenstar when you show your shieldmarshal badge), Climb +2, Craft (alchemy) +7, Craft (clockwork) +7, Craft (weapons) +5, Diplomacy +12 (+13 in Alkenstar when you show your shieldmarshal badge), Disable Device +10, Disguise +3 (+4 in Alkenstar when you show your shieldmarshal badge), Escape Artist +6, Fly +6, Handle Animal +6 (+7 in Alkenstar when you show your shieldmarshal badge), Heal +7, Intimidate +12 (+13 in Alkenstar when you show your shieldmarshal badge), Knowledge (engineering) +7, Knowledge (geography) +7, Knowledge (local) +9, Linguistics +2, Perception +19 (+20 when opposed by another creature's Disguise or Sleight of Hand checks), Profession (gambler) +8, Profession (Mercenary) +8, Ride +11, Sense Motive +12, Sleight of Hand +19, Stealth +13 (+14 when you have cover/concealment in an Urban area), Survival +8, Swim +2, Use Magic Device +5 (+6 in Alkenstar when you show your shieldmarshal badge)
Languages Auran, Common, Sylvan, Undercommon
SQ amazing initiative, danger sense, ghorus seed, gunmarshal, gunsmith, judgment of bulletproof, judgment of destruction, judgment of evasive, judgment of justice, judgment of lucky dodge, judgment of quick recovery, judgment of sharpshooter, judgment of sure shot, labyrinthine cunning, legal judgment, limitless range, past-life knowledge, pierce the darkness
Combat Gear arrowmaster's bracers, mariner's eyepatch; Other Gear celestial armor, +1 buckler, +3 reliable, greater pistol, buckler gun, cold iron dagger, dagger, dagger, dragon pistol, musket, paper cartridge (30), silver dagger, bandolier of incredible ant hauling dexterity +4, gloves of larceny, gunfighter's cloak of resistance +4, shackles ensign, cold weather outfit, 95,547 gp
Special Abilities
Amazing Initiative (1/round) (Ex) As a free action, use 1 power to gain an extra standard action (can't be used to cast a spell).
Clustered Shots Total damage from full-round ranged attacks before applying DR
Danger Sense (Ex) Can always act in the surprise round, even if unaware of foes.
Darkvision (120 feet) You can see in the dark (black and white only).
Deadly Aim -4/+8 Trade a penalty to ranged attacks for a bonus to ranged damage.
Deeds Use Grit to perform special abilities with your firearms.
Delicious (Ex) -2 penalty on Escape Artist and combat maneuver checks to escape bite grapples.
Distant Barrage (Ex) As a swift action, use 1 power for ranged att (+2 bonus, ignore cover/conceal & bypass all DR).
Ghorus Seed (Ex) As a full-rd action, create a seed which will grow new you in 2d6 days, but die when it sprouts.
Grit (Ex) Gain a pool of points that are spent to fuel deeds, regained on firearm crit/killing blow.
Gun Training On a misfire with chosen firearm type, misfire value only increase by 2 (instead of 4).
Gunmarshal +1 (Ex) Gain a bonus to Charisma skills in Alkenstar when show shieldmarshal badge.
Gunsmith Gain free starting firearm that only you can use properly.
Gunsmithing You can use a gunsmithing kit to craft/repair firearms and ammo.
Hard to Kill (Ex) Automatically stabilize when dying, and only die at neg Con x 2.
Judgment of Bulletproof (DR 1/- vs. ranged attacks) (Ex) Gain DR 1/- vs. ranged attacks, while wearing armor or a shield.
Judgment of Destruction +1 (Ex) Gain a bonus on firearm/light blade attacks, doubled to confirm crits when active.
Judgment of Evasive (Ex) Gain Evasion and Improved Uncanny Dodge when active.
Judgment of Justice +1 (Ex) Gain a bonus on firearm/light blade damage when active.
Judgment of Lucky Dodge +1 (Ex) Gain a dodge bonus to AC when active.
Judgment of Quick Recovery (Fast Healing 1) (Ex) Gain the listed amount of Fast Healing when active.
Judgment of Sharpshooter (Ignore 3 AC from cover) (Ex) Ignore the listed amount of AC from cover when active.
Judgment of Sure Shot (-5%) (Ex) Reduce miss chance due to concealment with firearms when active.
Labyrinthine Cunning (Ex) Can open doors as swift action. Never lost or slowed by poor visibility in urban areas.
Legal Judgment (1/day) (Ex) Variable bonuses increase as the combat continues.
Light Dependent (Ex) 1d4 Constitution damage per day without exposure to sunlight.
Limitless Range (Ex) Throw any melee weapon as if it had a range increment of 20 ft.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Nimble +3 (Ex) +3 AC while wearing light or no armor.
Past-Life Knowledge (Ex) Treat all Knowledge skills as class skills.
Point-Blank Shot +1 to attack and damage rolls with ranged weapons at up to 30 feet.
Precise Shot You don't get -4 to hit when shooting or throwing into melee.
Quick Draw Draw weapon as a free action (or move if hidden weapon). Throw at full rate of attacks.
Rapid Reload (Pistol) You can reload fast with one type of Crossbow or Firearm.
Rapid Shot [Mythic] Rapid shot allows 2 extra attacks, or 1 extra attack with no penalties.
Snap Shot Threaten squares within 5 feet of you when wielding a ranged weapon
Surge (1d6) (Su) Use 1 power to increase any d20 roll by the listed amount.
Vengeance (Ruben Goldblood) (Completed) +1 to att, dam, and saves vs. Ruben Goldblood and his minions.
```

Whew boy that's a long one. Anyway, this one seems to break on the multiclass lines - only works if I kill the prestige class and mythic rank entirely. Had the same issue with a Winter Witch NPC as well.

**Comment by Tristan-Goucher** [comment]
Here's my current statblock, taken from the first PDF from Return of the Runelords adventure path in PF1 (I did remove all of the linebreaks from PDF formatting):

`Lullaby Vancaskerkin CR 4
XP 1,200
Female human bard 5
CN Medium humanoid (human)
Init +2; Senses Perception +7
DEFENSE
AC 16, touch 13, flat-footed 13 (+3 armor, +2 Dex, +1 dodge)
hp 41 (4d8+23)
Fort +3, Ref +8, Will +3; +4 vs. bardic performance, language-dependent, and sonic
OFFENSE
Speed 30 ft
Melee rapier +5 (1d6/18–20)
Ranged dagger +5 (1d4/19–20)
Special Attacks bardic performance 15 rounds/day (countersong, distraction, fascinate [DC 15], inspire competence +2, inspire courage +2)
Bard Spells Known (CL 5th; concentration +8)
2nd (3/day)—daze monster (DC 15), invisibility, sound burst (DC 15)
1st (5/day)—cure light wounds, disguise self, grease, sleep (DC 14)
0 (at will)—daze (DC 13), ghost sound (DC 13), lullaby (DC 13), mending, message, prestidigitation
TACTICS
During Combat Lullaby starts combat with a bardic performance to inspire courage in herself and her allies, then hangs back to support them with spells, starting with daze monster. If possible, she saves sleep for occasions where the PCs are in a group. If engaged in combat, she does her best to flank with allies, but she prefers to stay at range and rely on her magic. If she and the Roadkeepers defeat the PCs, they rob them of all their coins and jewelry but leave them alive; in this case, Hallen crosses back over the river to help them get back on their feet.
Morale If the PCs defeat her Roadkeepers or reduce Lullaby to less than 20 hit points, she realizes she's in over her head. She cries out, "Oh! Sorry. . . here, have my magic coin and leave me alone!" as she tosses the copper piece she was flipping to the ground. The coin is not magic -- she's just trying to buy a few more precious seconds' head start as she runs away. She casts invisibility on herself as she fless if she can.
STATISTICS
Str 10, Dex 15, Con 14, Int 12, Wis 8, Cha 16
Base Atk +3; CMB +3; CMD 16
Feats Dodge, Lightning Reflexes, Lingering Performance, Weapon Finesse
Skills Acrobatics +10, Knowledge (engineering) +7, Knowledge (geography) +7, Knowledge (history) +7, Knowledge (local) +11, Knowledge (nature) +7, Knowledge (nobility) +7, Perception +7, Perform (sing) +11, Sleight of Hand +10, Stealth +10, Swim +5
Languages Common, Varisian
SQ bardic knowledge +2, lore master 1/day, versatile performance (sing)
Gear +1 leather armor, dagger (4), rapier, lucky blue hat (buffering cap), belt pouch, pearl (5) worth 50 gp each, 32 gp, 1 cp`

The output from the SBC Import window log:

`There were 2 issue(s) parsing the provided statblock:
    WARNING >> Parsing the tactics data failed at line 23 (non-critical)
    INFO >> Generated Placeholders for the following Entities: Lucky Blue Hat (buffering cap), Belt Pouch, Pearl (5) Worth 50 Gp Each, 32 Gp, 1 Cp`

The WARNING line is the Morale line of the tactics.
As for the INFO line, that's when parsing the Gear section. I _did_ notice that it doesn't parse plurals (for example, I had to change "daggers (4)" to "dagger (4)" for it to not have a placeholder generated. It also appears to not be accepting the currency as currency, or the belt pouch item. The buffering cap is almost certainly not in the PF1E system yet, and the way it's called in the statblock makes sense for why it wouldn't be detected.

**Comment by Camsycam** [comment]
![image](https://user-images.githubusercontent.com/77842382/106399182-69fac680-6417-11eb-8db5-20117a14597e.png)

**Comment by Camsycam** [comment]
![image](https://user-images.githubusercontent.com/77842382/106399365-6fa4dc00-6418-11eb-8c4e-a017bf53298d.png)

Sister of Eiseth CR 3
XP 800
Female human monk 4
LE Medium humanoid
Init +3; Senses Perception +8
DEFENSE
AC 16, touch 16, flat-footed 12 (+3 Dex, +1 dodge, +1 , +1 Wis)
hp 29 (4d8+8)
Fort +6, Ref +7, Will +5; +2 vs. enchantment
Defensive Abilities evasion, slow fall 20 ft., still mind
OFFENSE
Speed 40 ft.
Melee unarmed strike +6 (1d8+2) or flurry of blows +5/+5 (1d8+2) or mwk bladed scarf +7 (1d6+3)
Ranged mwk light crossbow +7 (1d8/19–20 plus poison)
Space 5 ft.; Reach 5 ft. (10 ft. with bladed scarf)
Special Attacks ki pool (3 points), stunning fist 4/day (stun or fatigue, DC 13)
TACTICS
During Combat Having trained together for hours on end, the Sisters work together in teams to harry their foes. Half of the Sisters fight defensively with a flurry of blows (+0/+0) using their ki pool to confer a +4 dodge bonus, further raising their total Armor Class to 23. The remaining Sisters attack from reach with their crimson habits, draining their ki pool to add a third attack to their flurry. Where possible they employ trip attacks to keep their foes off-balance.
Morale The Sisters fight to the death.
STATISTICS
Str 14, Dex 16, Con 15, Int 8, Wis 12, Cha 10
Base Atk +3; CMB +6; CMD 21
Feats Dodge, Exotic Weapon Proficiency (bladed scarf ), Improved Unarmed Strike, Iron Will, Scorpion Style, Stunning Fist, Weapon Finesse
Skills Acrobatics +10, Intimidate +7, Knowledge (religion) +6, Linguistics +0, Perception +8, Profession (mortician) +8
Languages Common, Infernal
Gear potion of cure moderate wounds, potion of lesser restoration; Other Gear masterwork bladed scarf, masterwork crossbow with 10 poisoned bolts (black adder venom—DC 11; 1/round for 6 rounds, 1d6 Con, 1 save)

**Comment by Raileth** [comment]
ive been trying to use the statblocks generated by herolab but have noticed the AC doesn't calculate correclty (seems to write the total ac from the statblock in @attributes.ac.normal.total and then apply any adjustments - thereby doubling the armor values / dex bonuses applied. Using herolab i have tried both generating the statblock with wearing armort and not wearing it.
Sample Statblock below:-

Kyra
Female human cleric of Sarenrae 1
NG Medium humanoid (human)
Init -1; Senses Perception +4
--------------------
Defense
--------------------
AC 15, touch 9, flat-footed 15 (+4 armor, -1 Dex, +2 shield)
hp 10 (1d8+2)
Fort +4, Ref -1, Will +7
--------------------
Offense
--------------------
Speed 30 ft. (20 ft. in armor)
Melee scimitar +1 (1d6+1/18-20)
Ranged light crossbow -1 (1d8/19-20)
Special Attacks channel positive energy 4/day (DC 11, 1d6 [+1 vs. undead]), sun's blessing
Domain Spell-Like Abilities (CL 1st; concentration +4)
   6/day—rebuke death (1d4)
Cleric Spells Prepared (CL 1st; concentration +4)
   1st—command (DC 14), divine favor, endure elements[D]
   0 (at will)—create water, detect magic, light
   D Domain spell; Domains Healing, Sun
--------------------
Statistics
--------------------
Str 13, Dex 8, Con 14, Int 10, Wis 17, Cha 12
Base Atk +0; CMB +1; CMD 10
Feats Channel Smite, Iron Will
Skills Acrobatics -5 (-9 to jump), Diplomacy +5, Heal +7, Knowledge (religion) +4, Perception +4
Languages Common
Other Gear chain shirt, heavy wooden shield, crossbow bolts (20), light crossbow, scimitar, backpack, silver holy symbol of Sarenrae, trail rations (6), 12 gp
--------------------
Special Abilities
--------------------
Channel Smite Channel energy can be delivered through a Smite attack.
Cleric Channel Positive Energy 1d6 (4/day, DC 11) (Su) Positive energy heals the living and harms the undead; negative has the reverse effect.
Cleric Domain (Healing) Granted Powers: Your touch staves off pain and death, and your healing magic is particularly vital and potent.
Cleric Domain (Sun) Granted Powers: You see truth in the pure and burning light of the sun, and can call upon its blessing or wrath to work great deeds.
Rebuke Death (6/day) (Sp) As a standard action, touch heals 1d4 dam to negative HP target.
Sun's Blessing (Su) +1 to channel damage vs. undead and they don't get channel resistance.
--------------------
Kyra was one of the few survivors of a brutal raid on her hometown, and on the smoking ruins of her village she swore her life and sword arm to Sarenrae. Possessed of a fierce will, pride in her faith, and skill with the scimitar, Kyra has traveled far since her trial by fire. She lost her family and home that fateful day, yet where another might be consumed by anger and a thirst for revenge, Kyra has found peace in the Dawnflower, and in the belief that, if she can prevent even one death at evil hands, her own losses will not have been in vain.

Hero Lab and the Hero Lab logo are Registered Trademarks of LWD Technology, Inc. Free download at https://www.wolflair.com
Pathfinder® and associated marks and logos are trademarks of Paizo Inc.®, and are used under license.

**Comment by adventuremagic123** [comment]
The spells and spell-likes don't import for this from Hero Lab:

Planetar (Angel)      CR 16
XP 76,800
Male planetar (Pathfinder RPG Bestiary 11)
NG Large outsider (angel, extraplanar, good)
Init +8; Senses darkvision 60 ft., detect evil, detect snares and pits, low-light vision, true seeing; Perception +27
Aura protective aura
--------------------
Defense
--------------------
AC 36, touch 17, flat-footed 32 (+4 deflection, +4 Dex, +19 natural, -1 size)
hp 229 (17d10+136); regeneration 10 (evil weapons and effects)
Fort +23, Ref +15, Will +23; +4 vs. poison
DR 10/evil; Immune acid, cold, petrification; Resist electricity 10, fire 10; SR 27
--------------------
Offense
--------------------
Speed 30 ft., fly 90 ft. (good)
Melee +3 holy greatsword +27/+22/+17/+12 (3d6+15/19-20 plus 2d6 vs. evil) or
   slam +19 (2d8+4)
Space 10 ft.; Reach 10 ft.
Spell-Like Abilities (CL 16th; concentration +23)
   Constant—detect evil, detect snares and pits, discern lies (DC 21), true seeing
   At will—continual flame, dispel magic, holy smite (DC 21), invisibility (self only), lesser restoration, remove curse, remove disease, remove fear, speak with dead (DC 20)
   3/day—blade barrier (DC 23), flame strike (DC 22), power word stun, raise dead, waves of fatigue
   1/day—earthquake, greater restoration, mass charm monster (DC 25), waves of exhaustion
Cleric Spells Prepared (CL 16th; concentration +23)
   8th—earthquake, fire storm (DC 25)
   7th—holy word (DC 24), regenerate (2)
   6th—banishment (DC 23), greater dispel magic, heal, mass inflict moderate wounds (DC 23)
   5th—break enchantment, dispel evil (2), plane shift (DC 22), righteous might
   4th—death ward, dismissal (DC 21), neutralize poison, summon monster IV
   3rd—cure serious wounds (2), daylight, invisibility purge, summon monster III, wind wall
   2nd—align weapon (2), bear's endurance (2), cure moderate wounds (2), eagle's splendor
   1st—bless (2), cure light wounds (4), shield of faith
   0 (at will)—detect magic, purify food and drink (DC 17), stabilize, virtue
--------------------
Statistics
--------------------
Str 27, Dex 19, Con 24, Int 22, Wis 25, Cha 24
Base Atk +17; CMB +26 (+28 sunder); CMD 44 (46 vs. sunder)
Feats Blind-fight, Cleave, Great Fortitude, Improved Initiative, Improved Sunder, Iron Will, Lightning Reflexes, Power Attack, Toughness
Skills Acrobatics +24, Craft (any one) +26, Diplomacy +27, Fly +26, Heal +24, Intimidate +27, Knowledge (history) +23, Knowledge (planes) +26, Knowledge (religion) +26, Perception +27, Sense Motive +27, Stealth +20
Languages Celestial, Draconic, Infernal; truespeech
SQ change shape (alter self)
Other Gear +3 holy greatsword
--------------------
Ecology
--------------------
Environment any good-aligned plane
Organization solitary or pair
Treasure double (+3 holy greatsword)
--------------------
Special Abilities
--------------------
Blind-Fight Re-roll misses because of concealment, other benefits.
Change Shape (alter self) (Su) You can change your form.
Cleave If you hit a foe, attack an adjacent target at the same attack bonus but take -2 AC.
Damage Reduction (10/evil) You have Damage Reduction against all except Evil attacks.
Darkvision (60 feet) You can see in the dark (black and white only).
Energy Resistance, Electricity (10) You have the specified Energy Resistance against Electricity attacks.
Energy Resistance, Fire (10) You have the specified Energy Resistance against Fire attacks.
Fly (90 feet, Good) You can fly!
Immunity to Acid You are immune to acid damage.
Immunity to Cold You are immune to cold damage.
Immunity to Petrification You are immune to Petrification.
Improved Sunder You don't provoke attacks of opportunity when sundering.
Low-Light Vision See twice as far as a human in dim light, distinguishing color and detail.
Poison Resistance +4 (Ex) You have the listed resistance to poison.
Power Attack -5/+10 You can subtract from your attack roll to add to your damage.
Protective Aura (+4, 20 ft.) (Su) Defense against evil creatures and lesser globe of invulnerability.
Regeneration 10 (evil weapons and effects) Heal HP quickly and cannot die.
Spell Resistance (27) You have Spell Resistance.
Truespeech (Su) Speak with any creature that has a language.

**Comment by adventuremagic123** [comment]
The following Hero Lab statblock did not import:

Derro      CR 3
XP 800
Male derro (Pathfinder RPG Bestiary 70)
CE Small humanoid (derro)
Init +6; Senses darkvision 60 ft.; Perception +0
--------------------
Defense
--------------------
AC 17, touch 13, flat-footed 15 (+2 armor, +2 Dex, +2 natural, +1 size)
hp 25 (3d8+12)
Fort +5, Ref +3, Will +6
SR 14
Weaknesses vulnerability to sunlight
--------------------
Offense
--------------------
Speed 20 ft.
Melee aklys +5 (1d4) or
   short sword +5 (1d4/19-20)
Ranged repeating light crossbow +5 (1d6/19-20)
Special Attacks sneak attack +1d6
Spell-Like Abilities (CL 3rd; concentration +6)
   At will—darkness, ghost sound (DC 13)
   1/day—daze (DC 13), sound burst (DC 15)
--------------------
Statistics
--------------------
Str 11, Dex 15, Con 18, Int 10, Wis 5, Cha 16
Base Atk +2; CMB +1; CMD 13
Feats Improved Initiative, Weapon Finesse
Skills Acrobatics +2 (-2 to jump), Perception +0, Stealth +9
Languages Aklo, Undercommon
SQ madness, poison use
Other Gear leather armor, aklys[UC], repeating light crossbow, short sword
--------------------
Ecology
--------------------
Environment any underground
Organization solitary, team (2-4), squad (5-8 plus 1 sorcerer of 3rd-5th level), or band (11-20 plus 30% noncombatants plus 3 sorcerers of 3rd-8th level)
Treasure npc gear (leather armor,  short sword or aklys, repeating  light crossbow with 10 poisoned  bolts, other treasure)
--------------------
Special Abilities
--------------------
Darkvision (60 feet) You can see in the dark (black and white only).
Madness (Ex) Immune to insanity and confustion effects.
Poison Use (Ex) You do not risk poisoning yourself accidentally while poisoning a weapon.
Sneak Attack +1d6 Attacks deal extra dam if flank foe or if foe is flat-footed.
Spell Resistance (14) You have Spell Resistance.
Vulnerability to Sunlight Natural sunlight deals 1 Con damage/hour exposed.

**Comment by adventuremagic123** [comment]
Looks pretty solid.  I'll have to try a lot harder to find more that don't import.  I've tried a variety of statblocks.  Good work!

**Comment by dmrickey** [comment]
```
ADHUKAIT JAILERS
XP 9,600 each
Adhukait magus 3
LE Medium outsider (asura, evil, extraplanar, lawful)
Init +4; Senses darkvision 60 ft.; Perception +24
Aura elusive (30 ft.)
DEFENSE
AC 24, touch 16, flat-footed 19 (+2 armor, +1 deflection, +4 Dex, +1 dodge, +6 natural)
hp 137 each (12 HD; 3d8+9d10+75); regeneration 5 (good weapons, good spells)
Fort +11, Ref +13, Will +14; +2 bonus vs. enchantment spells
Defensive Abilities all-around vision, dual mind; DR 5/good;
Immune curse effects, disease, flanking, poison; Resist
acid 10, electricity 10; SR 18
OFFENSE
Speed 40 ft.
Melee +1 kukri +19/+14/+9 (1d4+8/18–20), 2 claws +13 (1d4+3)
Special Attacks arcane pool (+1, 2 points), dance of disaster,
magus arcana (pool strike), spell combat, spellstrike
Spell-Like Abilities (CL 6th; concentration +8)
At will—feather fall, greater teleport (self plus 50 lbs. of objects only), spider climb
3/day—blink, blur, mirror image, spike growth (DC 14)
1/day—summon (level 4, 1 adhukait 35%)
Magus Spells Prepared (CL 3rd; concentration +4)
1st—burning hands (DC 12), magic missile, shocking grasp, true strike
0 (at will)—acid splash, detect magic, open/close (DC 11), ray of frost
TACTICS
During Combat An adhukait jailer casts mirror image on the first round of combat and then makes use of spellstrike to combine kukri attacks with damaging spells. Morale The jailers fight to the death.
STATISTICS
Str 24, Dex 19, Con 20, Int 13, Wis 21, Cha 14
Base Atk +11; CMB +18; CMD 34
Feats Combat Reflexes, Dodge, Lightning Reflexes, Mobility, Nimble Moves, Toughness
Skills Acrobatics +17, Bluff +15, Escape Artist +16,
Intimidate +17, Knowledge (planes) +9, Perception +24,
Perform (dance) +13, Stealth +16
Languages Common, Infernal; telepathy 100 ft.
Gear +1 kukri, bracers of armor +2, ring of protection +1, spellbook
```
![image](https://user-images.githubusercontent.com/3664822/109093934-d39c8680-76de-11eb-936b-2c079ac43340.png)
![image](https://user-images.githubusercontent.com/3664822/109094050-02b2f800-76df-11eb-881d-8007a6c3ffc8.png)
- It says it failed to parse the description but the preview has the whole thing just fine (at least as far as I can tell, maybe there's some whitespace in there that's broken or something)
- No magus class at all, but it correctly pulled in the 9 racial hit die
- No spells pulled in

**Comment by Lavaeolous** [comment]
New Issue for broken statblocks was created.
You may need to re-install sbc as the manifest file changed and rerun the import. There were some fixes in the meantime.
