### ISSUE TITLE
Armor and Shields are being double counted

### ISSUE THREAD

**Issue by AlphaQup2nite** [Lavaeolous/PF1-StatBlock-Converter-Module#362]
https://www.d20pfsrd.com/bestiary/npc-s/npcs-cr-1/caravan-guard-human-fighter-2/

This block creates a conversion buff with the armor and shield buff, and is also equiping them with the items in the inventory, applying 2x for armor and sheild bonuses in the final calculation.

**Comment by AlphaQup2nite** [comment]
this is applying to dodge bonuses as well.

**Comment by Lavaeolous** [comment]
Ah, this again. SBC checks the items an actor has for changes to specific values, like armor. I *think* this might be another timing or sync/async error, as the item-changes might not be available in the actor when sbc checks them for the conversion buff.

**Comment by Lavaeolous** [comment]
Okay, its not an async error, but shields and armor no longer include these attribute changes as changes, but include them in the item details

**Comment by Lavaeolous** [comment]
Could not fix this for 3.0.2, will be delayed for 3.0.3

**Comment by Lavaeolous** [comment]
Okay, there was time for a hotfix to this in 3.0.2. This should prevent gross errors, but needs further testing down the line.

**Comment by Lavaeolous** [comment]
I've reworked the conversion validation, so that different ac types (like armor, shield, deflection, dodge, ...) get validated first. After that the current total gets validated against the value initially found in the statblock and any differences get included in an change in the conversion buff.

Will be online in v3.0.3
