### ISSUE TITLE
Please stop force indexing everything at world launch

### ISSUE THREAD

**Issue by mkahvi** [Lavaeolous/PF1-StatBlock-Converter-Module#493]
While SBC is enabled, all the compendiums are force indexed for all users and is causing some serious loading issues.

Even if desirable, I believe this should be limited to users who pass .isGM check, but even then I feel like the indexing should be done only on demand, not pre-emptively.

> SBC 3.3.2, PF1 0.79.10, Foundry 0.8.9

**Comment by Lavaeolous** [comment]
Disabled in 3.3.3. This was needed in the past, as the search for items in compendia needed a built index. Seems the work @JustNoon did with the system-function `findInCompendia()` removed the need for pre-built indices, so i disabled it for now. Let me know if something brakes because of this, in my tests everything seems to work fine.
