### ISSUE TITLE
Parsing gear adds placeholders even though all items can be found

### ISSUE THREAD

**Issue by KayelGee** [Lavaeolous/PF1-StatBlock-Converter-Module#504]
The following line taken from https://www.d20pfsrd.com/bestiary/npc-s/npcs-cr-3/guard-officer-human-fighter-4/
(nets have been changed to net) will cause Placeholders to be generated for Javelin and Sap:
`Combat Gear potion of cure light wounds; Other Gear full plate, masterwork guisarme, javelin, net (2), sap`
when you remove the masterwork guisarme it'll generate no placeholders. Everything seems valid and will be found on it's own but in this combination it doesn't.

**Comment by Lavaeolous** [comment]
The error seems to be with the `guisarme` and not the masterwork state. When the guisarme is included in the statblock (regardless of mwk or not), the following items are handled as from type loot (and no longer as type weapon), which will lead to a failed search (as sbc is then not searching the weapons-ammo compendium.

**Comment by Lavaeolous** [comment]
Ok, there's something very funky going on. Currently it seems that every second item parsed defaults to the `loot` type. I'll investigate further.

**Comment by Lavaeolous** [comment]
The bug is related to the `pattern.test(input)` method, which seems to increase an index everytime it results in `true`, which in turn breaks the following use of test (as the input now starts at a wrong index, e.g. `ull plate` instead of `full plate`).

When `test` returns false, this index gets reset, which is why the following use will work again.

I'll check if i can circumvent this somehow or if i need to switch back to another regex-matching method.

**Comment by Lavaeolous** [comment]
Fixed in 3.3.5
